# Generated by Django 3.1.5 on 2021-01-13 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(days=7)),
            preserve_default=False,
        ),
    ]
